kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

workspace:
  path: /usr/local/app

steps:
- name: build
  image: golang:1.13.7
  commands:
  - go test ./...
  - go build
- name: notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
    channel: website
  when:
    status:
    - failure
    - success

deploy:
  rancher:
    image: pelotech/drone-rancher
    url: https://ec2-54-188-42-26.us-west-2.compute.amazonaws.com/v3
    access_key: token-kfk26
    secret_key: 7wvrzz4rrcz9lpgmlkxggw96w6vdj59g96tf2d4pq8v65fnd85hdrq
    service: bihicheng/hello
    sidekick: nginx nginx:latest
    sidekick: node node:latest
    docker_image: bihicheng/hello:latest

trigger:
  branch:
  - master
  event:
  - push
  - pull_request
