kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

workspace:
  path: /usr/local/app

steps:
- name: build
  image: golang:1.13.7
  commands:
  - go test ./...
  - go build

- name: publish
  image: plugins/docker
  settings:
    repo: bihicheng/hello
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: username
    password:
      from_secret: password

- name: release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files: hello
  when:
    event: tag

trigger:
  branch:
  - master
  - dev
  event:
  - push
  - pull_request
