kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

workspace:
  path: /usr/local/app

steps:
- name: build
  image: golang:1.13.7
  commands:
  - go test ./...
  - go build

trigger:
  branch:
  - master
  event:
  - push
  - pull_request
