stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.17.3
      shellScript: |-
        mkdir -p /go/src/github.com/rancher
        ln -s `pwd` /go/src/github.com/rancher/hello
        cd /go/src/github.com/rancher/hello
        go build -o bin/hello
        go test -cover
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: hello:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
